image: docker:latest
variables:
  DOCKER_DRIVER: overlay
  CRYPTOGRAPHY_DONT_BUILD_RUST: 1
services:
  - docker:dind

before_script:
    - apk update
    - apk upgrade
    - apk add wget
    - apk add nginx
    - apk add php7 php7-fpm php7-opcache
    - apk add php7-openssl php7-json php7-phar php7-iconv php7-mbstring
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - HASH="$(wget -q -O - https://composer.github.io/installer.sig)"
    - php -r "if (hash_file('SHA384', 'composer-setup.php') === '$HASH') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
    - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
    - composer
    - wget https://get.symfony.com/cli/installer -O - | bash
    - mv /root/.symfony/bin/symfony /usr/local/bin/symfony
    - symfony server:ca:install

stages:
  - install
  - build-docker

install-dependencies:
  stage: install
  script:
    - composer install

build-docker:
  stage: build-docker
  dependencies:
    - install-dependencies
  script:
    - docker build . -t=php-with-composer-web