version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-with-composer-web
    volumes: 
      - ".:/app"
    ports:
      - "8001:8000"
    tty: true